Milestone1 basic project structure
DanielMitiku/calculator-react pull request #1
Opened 2020-01-17 18:32 UTC by DanielMitiku

Finished basic project setup and ready to go on!

2020-01-17 20:12 UTC, jofer86 requested changes
## 👋 👋 Hello I'll be reviewing your PR. Let's take a look 👁 👁 👁  , shall we? 

- As the instructions for this project explains we need to remove all of the unnecessary files the CRA tools generate. 
![image](https://user-images.githubusercontent.com/46115725/72642986-44e20580-3933-11ea-8a1d-01358c52bb94.png)
- Below I commented on the files that need deletion, if you find extra files that are not going to be used please do delete them and ask for a new code review!
- And also let's make sure our app is deployed to Heroku as the instructions say, and provide the link for the live app, even though it might not contain much we need to make sure is up there.

2020-01-17 20:12 UTC, jofer86 commented on src/App.js
> +
Here we should render just an empty div, with no content inside, also we need to get rid of all unnecessary files, that is the logo image, service workers, we should only be left off with a div with a class of App and nothing rendered inside.

2020-01-17 20:12 UTC, jofer86 commented on src/App.test.js
> +});
Let's remove this file, unless you are planning on doing testing

2020-01-17 20:12 UTC, jofer86 commented on src/index.js
> +serviceWorker.unregister();
let's remove this line as well

2020-01-17 20:12 UTC, jofer86 commented on src/index.js
> +import * as serviceWorker from './serviceWorker';
let's remove this line, as we are not using service workers

2020-01-17 20:12 UTC, jofer86 commented on src/logo.svg
> +</svg>
Let's remove this file as we are not using it

2020-01-17 20:12 UTC, jofer86 commented on src/serviceWorker.js
> +}
Lets remove this file as we are not using it also.

2020-01-17 20:12 UTC, jofer86 commented on src/setupTests.js
> +import '@testing-library/jest-dom/extend-expect';
This file needs to go too. We are not using it.

2020-01-17 20:12 UTC, jofer86 commented on src/App.css
> +}
Let's delete this file too, or the contents as the styling done here is not relevant for the project.

2020-01-17 20:12 UTC, jofer86 commented on public/robots.txt
> +User-agent: *
Let's delete this file also.

2020-01-18 07:13 UTC, DanielMitiku commented
I've removed unnecessary files. The app has been deployed to heroku. The link is found in the readme of the milestone1 branch.

2020-01-20 08:40 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next milestones. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2020-01-20 09:22 UTC, merged