Milestone5 event handlers
DanielMitiku/calculator-react pull request #5
Opened 2020-01-23 13:59 UTC by DanielMitiku

Full functionalities of the calculator app have been implemented.

2020-01-23 18:26 UTC, bellom requested changes
## Hi @DanielMitiku  :clap: 

### Awesome job so far!! :+1: 

##### You have done wonderfully well, you passed all checklist for this project :+1: 

1. **Kindly watch and listening carefully to the video and audio code review below;**
[Video Link](https://www.loom.com/share/78b6e13547db4158b1bf8448fc6c8589)
**_Hope it helps clarify the issues we are having ......_**

2. README file not detailed enough. (you can add steps to git clone your repo, necessary installation and live link)
Remove the default `readme` content
Kindly watch the video tutorial on how to create live link below 👇;
[Video Link](https://www.loom.com/share/76088842a2d14322bbcf65b884f4d42d)
checkout out the below link for help, free to follow the template from the pathwright
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-23 18:27 UTC, bellom commented on src/logic/calculate.js
>        } if (bName === '.') {
whenever `bName === .`  we should be able to return `0.` not `.`
I think the app doesn't look professional like that right?

Screenshot from your app below 👇
![image](https://user-images.githubusercontent.com/31897434/73010494-d4475700-3e12-11ea-82ed-d239f6699b39.png)

2020-01-23 19:39 UTC, bellom commented on src/logic/calculate.js
>          };
Whenever the `AC` button is  clicked, we should have `0` as the result right.... shown in the loom video

2020-01-23 19:44 UTC, DanielMitiku commented
I've made the changes for the comments given. Thank you.

2020-01-24 10:38 UTC, shloch approved these changes
## Hello @DanielMitiku 

PROJECT COMPLETE
## 👏👏👏👏👏👏👏👏👏👏👏👏

SEE YOU ON NEXT PROJECT

2020-01-24 11:05 UTC, DanielMitiku commented
Thank you!

2020-01-24 11:05 UTC, merged